version: '3.8'

services:
  frontend:
    image: scjdemoregistry.azurecr.io/frontend:latest # <--- ADD THIS LINE
    # build: # <--- REMOVE OR COMMENT OUT THIS BLOCK FOR DEPLOYMENT
    #   context: ./frontend
    #   dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_BACKEND_URL=http://backend:5001
    depends_on:
      - backend

  backend:
    image: scjdemoregistry.azurecr.io/backend:latest # <--- ADD THIS LINE
    # build: # <--- REMOVE OR COMMENT OUT THIS BLOCK FOR DEPLOYMENT
    #   context: ./backend
    #   dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=production # Ensure this is production
      - FLASK_APP=app.py
      # - DATABASE_URL=... (for later)